
ExternalProject_Add (ERS
  DEPENDS ${DEPENDENCIES}
  SOURCE_DIR ${PROJECT_SOURCE_DIR}
  CMAKE_ARGS -DUSE_SUPERBUILD=OFF ${EXTRA_CMAKE_ARGS}
  INSTALL_COMMAND ""
  BUILD_ALWAYS 1
  # BINARY_DIR ${CMAKE_CURRENT_BINARY_DIR}/ERS
)
