name: Windows

on: [push]

jobs:
  Build_Test:
    runs-on: windows-latest
    strategy:
        matrix:
            build_type: [Debug, Release]
    steps:
    - uses: actions/checkout@v2
    
    - name: Create Build Environment
      working-directory: ${{github.workspace}}/FreeImage
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory build
     
    - name: Generate a buildsystem for Windows
      shell: bash
      working-directory: ${{github.workspace}}/FreeImage/build
      run: cmake .. -G "Visual Studio 16 2019" -A x64 -DCMAKE_CONFIGURATION_TYPES:STRING=${{matrix.build_type}}
  
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Build using MSBuild
      working-directory: ${{github.workspace}}/FreeImage/build
      run: msbuild -m -p:"Configuration=${{matrix.build_type}};Platform=x64" ALL_BUILD.vcxproj
    
    - name: Test
      shell: bash
      working-directory: ${{github.workspace}}/FreeImage/build
      run: ctest -C ${{matrix.build_type}}
