###########################################################################################################
# This configuration file is an ERS editor layout, and specifies what windows should be enabled/disabled. #
# All other window info is stored in the associated .ini file.                                            #
###########################################################################################################


